application: bulletchina
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/faviconnew.ico
  static_files: static/faviconnew.ico
  upload: static/faviconnew.ico
  
- url: /static
  static_dir: static

- url: .*
  script: myweb.py
